### ISSUE TITLE
Migrate to transparency-dev/merkle

### ISSUE THREAD

**Issue by pavelkalinnikov** [letsencrypt/ct-woodpecker#121]
Hi team,

I [observe](https://github.com/letsencrypt/ct-woodpecker/search?q=merkle) you are using a mix of `merkle` packages:
- [one](https://github.com/google/trillian/tree/master/merkle) from Trillian, and
- https://github.com/transparency-dev/merkle.

We are [in the process](https://github.com/google/trillian/pull/2715) of decommissioning the `merkle` package from Trillian, as all our code (including Trillian itself) is now using `transparency-dev/merkle`. The new repository is well maintained, and we are also going to document some best practices on Merkle tree implementations.

Consider migrating your code fully to `transparency-dev/merkle`. Happy to help if you have questions on how to do it.

Thank you.

**Comment by jsha** [comment]
Thanks! We'll make the switch.

**Comment by aarongable** [comment]
It appears that the version of Trillian which now uses transparency-dev/merkle has not been tagged and released.

This causes problems, particularly in places like [here](https://github.com/google/trillian/blob/master/storage/tree/node.go), where Trillian's data structure has been updated to contain a `transparency-dev/merkle/compact.NodeID`, but the version of Trillian which has been released (and which ct-woodpecker therefore relies on) [still uses the internal type](https://github.com/google/trillian/blob/v1.4.0/storage/tree/node.go). This leads to issues like:

![image](https://user-images.githubusercontent.com/2474926/166313902-b4762212-694c-4228-b913-feba78fa1492.png)

Please tag a new Trillian release so that we can update to that version and smoothly make this transition.

**Comment by pavelkalinnikov** [comment]
Thanks for flagging this. We were planing a release anyway, so it will be fixed soon.
